'use client'

import React, { useState } from 'react';
import { Breadcrumb, Layout, Menu, theme } from 'antd';
// import type { Metadata } from "next";
import { items } from "./sidebarMenu"
// import { Inter } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const { Header, Content, Footer, Sider } = Layout;

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function DefaultLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [collapsed, setCollapsed] = useState(false);
    const {
        token: { colorBgContainer, borderRadiusLG },
    } = theme.useToken();

    return (
        // <html lang='en'>
            // <body className={inter.className}>
                // <AntdRegistry>
                    <Layout style={{ minHeight: '100vh' }}>
                        <Header style={{ padding: 0 }} />
                        <Layout>
                            <Sider collapsible collapsed={collapsed} onCollapse={(value) => setCollapsed(value)}>
                                <div className="demo-logo-vertical" />
                                <Menu theme="dark" defaultSelectedKeys={['1']} mode="inline" items={items} />
                            </Sider>

                            <Content style={{ margin: '0 16px' }}>
                                <Breadcrumb style={{ margin: '16px 0' }}>
                                    <Breadcrumb.Item>User</Breadcrumb.Item>
                                    <Breadcrumb.Item>Bill</Breadcrumb.Item>
                                </Breadcrumb>
                                <div
                                    style={{
                                        padding: 24,
                                        minHeight: 360,
                                        background: colorBgContainer,
                                        borderRadius: borderRadiusLG,
                                    }}
                                >
                                    {children}
                                </div>
                            </Content>
                        </Layout>
                    </Layout>
                // </AntdRegistry>
            // </body>
        // </html>

    );
};

// export default DefaultLayout;